
#ifndef __IC_LIBS__FS__FS_ERR_H
#define __IC_LIBS__FS__FS_ERR_H

/** Коды ошибок. */
enum {
	FS_OK = 0,
	FS_ERR_UNDEF,
	FS_ERR_PARAM,
	FS_ERR_NO_MEM,
	FS_ERR_NOT_FOUND,
	FS_ERR_INVALID_FORMAT,
	FS_ERR_NOT_IMPL,
	FS_ERR_NO_ENT,
	FS_ERR_TIMED_OUT,
	FS_ERR_BUSY,
	FS_ERR_EXIST,
	FS_ERR_LOOP,
	FS_ERR_NAMETOOLONG,
	FS_ERR_BUFFER_OVERFLOW
};

#endif /* __IC_LIBS__FS__FS_ERR_H */
